#!/usr/bin/env bash
set -eu

function gen() {
	local n=$1
	local layout=$2
	echo "============================= $1 ($2) ============================="
	local template
	template="$(hostname -s)"
	if [[ "$template" == mix4 ]] ; then
		if [[ "$layout" == *'(dvorak)' ]] ; then
			template="$template"-dv
		else
			template="$template"-us
		fi
	fi
	sed "s/LAYOUT/$layout/g" < template-"$template".xkb > layout-"$n".xkb
	if command -v xkbcomp > /dev/null ; then
		xkbcomp -I. layout-"$n".xkb layout-"$n".xkm
	else
		echo "xkbcomp not found, skipping layout compilation" >&2
	fi
}

gen 1 'us(dvorak)'
gen 2 'us'
gen 3 'my_ru(dvorak)'
gen 5 'my_ro(dvorak)'
gen 6 'ru'
