#!/bin/bash
set -eu

function gen() {
	echo "============================= $1 ($2) ============================="
	sed "s/LAYOUT/$2/g" < template-"$(hostname -s)".xkb > layout-"$1".xkb
	xkbcomp -I. layout-"$1".xkb layout-"$1".xkm
}

gen 1 'us(dvorak)'
gen 2 'us'
gen 3 'my_ru(dvorak)'
gen 4 'my_ro(dvorak)'
gen 6 'ru'
